### ISSUE TITLE
com.google.HTTPStatus error 400

### ISSUE THREAD

**Issue by marathia** [yourhead/rapidblog#8]
I'm no longer able to (re-)sync with Blogger, manually or through publishing. I get the error message:
> The operation couldn’t be completed. (com.google.HTTPStatus error 400.)

**Comment by yourhead** [comment]
The bug reporter isn't really good at dealing with support requests like this.  Perhaps contact http://yourhead.com/support -- or refile with more specific info that helps us duplicate the issue. thx.
